name = "textpile"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# Durable Objects
[durable_objects]
bindings = [
  { name = "POST_ID_ALLOCATOR", class_name = "PostIdAllocator" }
]
